### PR TITLE
add support for MAC to stdSettings.cls -pb

### PR DESCRIPTION
**Pull request by lopperman**
Add support for mac (look for '#If Mac' to see specific changes), primarily
 - declare 'pSettingsCache' as Dictionary object, if MAC
 - instantiate new 'pSettingsCache' as new Dictionary in 'Create' method, if MAC
 - Modify attempting to set new worksheet codeName to only run if NOT Mac
 - Modify GetIdentity -- Mac uses 'LOGNAME' instead of 'USERNAME'; MAC doesn't have 'USERDNSDOMAIN', so changed to use SandBox App Group ID; 
 - Recommend always using 'Application.PathSeparator' intead of hard-coded "\" or "/"

### CODE REVIEW

**Comment by sancarn** [comment]
Hey! PR looks good/setup correctly.

I'd like to remove the need for dependencies. Could we generally use a collection instead of a dictionary? I think this would be more ideal than including Tim He's dictionary class.

**Comment by lopperman** [comment]
Yes, I could switch to a Collection -- just want to confirm you know the dependency is Mac only, right?  (Most Mac users will either have that Dictionary class, or be happy to get it.  Unless I hear otherwise, I'll make the changes to remove the Dict dependency

**Comment by sancarn** [comment]
> just want to confirm you know the dependency is Mac only, right?

Yes understand that, still think we should remove dependencies where possible, and in this case it is possible. Not sure what the performance detriments are of using collections, but I know Tim's class uses collections anyway so from that angle there'd be no performance loss.

**Comment by lopperman** [comment]
I committed the changes to remove the Dictionary Dependency.  It looks like that just gets added to my first pull request.  Is there anything else I need to do?

**Comment by lopperman** [comment]
@sancarn  I didn't convert the 'PC' code to use the Collection, I'd feel more comfortable if you made those changes.  At the least, still need to use precompiler directives for the GetIdentify and ignore worksheet codename for Mac (it still stops the code even with 'On Error Resume Next').  Other than that all the code could be cross platform (probably want to change the name of 'MACKeyExists' function to 'KeyExists' or something)

**Comment by sancarn** [comment]
> I didn't convert the 'PC' code to use the Collection, I'd feel more comfortable if you made those changes.

Sure that's fine by me 👍 Let me know when you've finished and I'll merge 😄

**Comment by lopperman** [comment]
Should be good to go

**Comment by sancarn** [comment]
Congrats on your first PR 😄

**Pull request merged**
